-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  achievement_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  badge_name character varying NOT NULL,
  badge_icon text,
  badge_category character varying CHECK (badge_category::text = ANY (ARRAY['workouts'::character varying, 'streaks'::character varying, 'goals'::character varying, 'milestones'::character varying, 'social'::character varying, 'special'::character varying]::text[])),
  description text,
  criteria_type character varying,
  criteria_value integer,
  current_progress integer DEFAULT 0,
  target_progress integer NOT NULL,
  progress_percentage numeric DEFAULT 0,
  is_earned boolean DEFAULT false,
  earned_date timestamp with time zone,
  display_order integer DEFAULT 0,
  rarity character varying CHECK (rarity::text = ANY (ARRAY['common'::character varying, 'rare'::character varying, 'epic'::character varying, 'legendary'::character varying]::text[])),
  points_value integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT achievements_pkey PRIMARY KEY (achievement_id),
  CONSTRAINT achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_fitness_summary (
  summary_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  summary_text text NOT NULL,
  goal_progress_percentage numeric,
  predicted_goal_completion_date date,
  ai_recommendation text,
  weekly_progress_summary text,
  monthly_progress_summary text,
  strengths jsonb,
  improvement_areas jsonb,
  generated_at timestamp with time zone DEFAULT now(),
  is_current boolean DEFAULT true,
  version integer DEFAULT 1,
  CONSTRAINT ai_fitness_summary_pkey PRIMARY KEY (summary_id),
  CONSTRAINT ai_fitness_summary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.body_stats (
  stat_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  recorded_date date DEFAULT CURRENT_DATE,
  weight_kg numeric,
  bmi numeric,
  body_fat_percentage numeric,
  muscle_mass_kg numeric,
  body_water_percentage numeric,
  bone_mass_kg numeric,
  chest_cm numeric,
  waist_cm numeric,
  hips_cm numeric,
  arms_cm numeric,
  legs_cm numeric,
  neck_cm numeric,
  heart_rate_bpm integer,
  resting_heart_rate_bpm integer,
  blood_pressure_systolic integer,
  blood_pressure_diastolic integer,
  hydration_level_ml integer,
  calories_burned_today integer DEFAULT 0,
  steps_count integer DEFAULT 0,
  active_minutes integer DEFAULT 0,
  sleep_hours numeric,
  stress_level integer CHECK (stress_level >= 1 AND stress_level <= 10),
  source character varying DEFAULT 'manual'::character varying CHECK (source::text = ANY (ARRAY['manual'::character varying, 'wearable'::character varying, 'ai_estimation'::character varying]::text[])),
  device_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT body_stats_pkey PRIMARY KEY (stat_id),
  CONSTRAINT body_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.booking_cancellations (
  cancel_id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  user_id uuid NOT NULL,
  canceled_by character varying NOT NULL CHECK (canceled_by::text = ANY (ARRAY['user'::character varying, 'trainer'::character varying, 'gym'::character varying, 'admin'::character varying, 'system'::character varying]::text[])),
  cancel_reason_category character varying CHECK (cancel_reason_category::text = ANY (ARRAY['personal'::character varying, 'illness'::character varying, 'emergency'::character varying, 'schedule_conflict'::character varying, 'trainer_unavailable'::character varying, 'gym_closed'::character varying, 'weather'::character varying, 'other'::character varying]::text[])),
  cancel_reason text NOT NULL,
  cancellation_type character varying CHECK (cancellation_type::text = ANY (ARRAY['full_cancel'::character varying, 'reschedule_request'::character varying, 'no_show'::character varying]::text[])),
  reschedule_requested boolean DEFAULT false,
  new_booking_id uuid,
  rescheduled_to_date date,
  rescheduled_to_time time without time zone,
  reschedule_reason text,
  refund_eligible boolean DEFAULT true,
  refund_amount numeric DEFAULT 0.00,
  refund_percentage numeric,
  refund_status character varying DEFAULT 'pending'::character varying CHECK (refund_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'rejected'::character varying, 'not_applicable'::character varying]::text[])),
  refund_transaction_id uuid,
  refund_method character varying CHECK (refund_method::text = ANY (ARRAY['original_payment'::character varying, 'wallet'::character varying, 'bank_transfer'::character varying, 'credit'::character varying, 'none'::character varying]::text[])),
  cancellation_fee numeric DEFAULT 0.00,
  fee_reason text,
  hours_before_session integer,
  within_free_cancellation_window boolean,
  canceled_at timestamp with time zone DEFAULT now(),
  refund_processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_cancellations_pkey PRIMARY KEY (cancel_id),
  CONSTRAINT booking_cancellations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT booking_cancellations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT booking_cancellations_new_booking_id_fkey FOREIGN KEY (new_booking_id) REFERENCES public.bookings(booking_id)
);
CREATE TABLE public.booking_details (
  detail_id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  trainer_name character varying,
  trainer_bio text,
  trainer_specialization character varying,
  trainer_photo_url text,
  trainer_rating numeric,
  trainer_total_sessions integer,
  trainer_notes text,
  gym_name character varying,
  gym_address text,
  gym_phone character varying,
  gym_location jsonb,
  gym_facilities jsonb,
  workout_plan_pdf_url text,
  nutrition_plan_pdf_url text,
  session_goals jsonb,
  expected_intensity character varying CHECK (expected_intensity::text = ANY (ARRAY['low'::character varying, 'moderate'::character varying, 'high'::character varying, 'very_high'::character varying]::text[])),
  equipment_needed jsonb,
  equipment_provided_by_gym boolean DEFAULT true,
  bring_own_equipment text,
  pre_session_weight_kg numeric,
  post_session_weight_kg numeric,
  pre_session_heart_rate integer,
  post_session_heart_rate integer,
  hydration_ml integer,
  wearable_data_id uuid,
  wearable_device_used character varying,
  wearable_sync_completed boolean DEFAULT false,
  attachments jsonb,
  payment_invoice_id uuid,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_details_pkey PRIMARY KEY (detail_id),
  CONSTRAINT booking_details_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id)
);
CREATE TABLE public.booking_history (
  booking_history_id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  user_id uuid NOT NULL,
  completion_status character varying NOT NULL CHECK (completion_status::text = ANY (ARRAY['completed'::character varying, 'missed'::character varying, 'partially_completed'::character varying, 'canceled'::character varying]::text[])),
  attended boolean DEFAULT false,
  calories_burned integer CHECK (calories_burned >= 0),
  session_duration_actual integer,
  distance_km numeric,
  average_heart_rate integer,
  max_heart_rate integer,
  trainer_rating integer CHECK (trainer_rating >= 1 AND trainer_rating <= 5),
  gym_rating integer CHECK (gym_rating >= 1 AND gym_rating <= 5),
  overall_rating integer CHECK (overall_rating >= 1 AND overall_rating <= 5),
  user_feedback text,
  feedback_submitted_at timestamp with time zone,
  performance_score integer CHECK (performance_score >= 0 AND performance_score <= 100),
  performance_analysis text,
  session_summary_notes text,
  exercises_performed jsonb,
  achievements_earned jsonb,
  wearable_data_id uuid,
  wearable_sync_status character varying CHECK (wearable_sync_status::text = ANY (ARRAY['synced'::character varying, 'pending'::character varying, 'failed'::character varying, 'not_available'::character varying]::text[])),
  session_started_at timestamp with time zone,
  session_ended_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_history_pkey PRIMARY KEY (booking_history_id),
  CONSTRAINT booking_history_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT booking_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.booking_notifications (
  notification_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  booking_id uuid,
  message text NOT NULL,
  title character varying,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['reminder'::character varying, 'confirmation'::character varying, 'update'::character varying, 'cancellation'::character varying, 'reschedule'::character varying, 'refund'::character varying, 'feedback_request'::character varying, 'check_in'::character varying, 'session_starting'::character varying, 'session_ended'::character varying, 'trainer_message'::character varying]::text[])),
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  read_status boolean DEFAULT false,
  read_at timestamp with time zone,
  sent_via_push boolean DEFAULT false,
  push_sent_at timestamp with time zone,
  sent_via_email boolean DEFAULT false,
  email_sent_at timestamp with time zone,
  sent_via_sms boolean DEFAULT false,
  sms_sent_at timestamp with time zone,
  requires_action boolean DEFAULT false,
  action_type character varying,
  action_url text,
  action_completed boolean DEFAULT false,
  action_completed_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  sent boolean DEFAULT false,
  metadata jsonb,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_notifications_pkey PRIMARY KEY (notification_id),
  CONSTRAINT booking_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT booking_notifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id)
);
CREATE TABLE public.bookings (
  booking_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  trainer_id uuid,
  session_id uuid,
  session_type character varying NOT NULL CHECK (session_type::text = ANY (ARRAY['in_person'::character varying, 'virtual'::character varying, 'hybrid'::character varying]::text[])),
  session_category character varying CHECK (session_category::text = ANY (ARRAY['personal_training'::character varying, 'group_class'::character varying, 'gym_access'::character varying, 'consultation'::character varying, 'other'::character varying]::text[])),
  session_name character varying,
  session_description text,
  session_date date NOT NULL,
  session_time time without time zone NOT NULL,
  session_datetime timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
  end_datetime timestamp with time zone,
  status character varying DEFAULT 'upcoming'::character varying CHECK (status::text = ANY (ARRAY['upcoming'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'canceled'::character varying, 'rescheduled'::character varying, 'no_show'::character varying, 'pending_confirmation'::character varying]::text[])),
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'partially_paid'::character varying, 'refunded'::character varying, 'failed'::character varying]::text[])),
  payment_amount numeric NOT NULL CHECK (payment_amount >= 0::numeric),
  currency character varying DEFAULT 'USD'::character varying,
  transaction_id uuid,
  checked_in boolean DEFAULT false,
  check_in_time timestamp with time zone,
  check_in_method character varying CHECK (check_in_method::text = ANY (ARRAY['qr_code'::character varying, 'manual'::character varying, 'auto'::character varying, 'nfc'::character varying]::text[])),
  virtual_meeting_url text,
  virtual_meeting_id character varying,
  virtual_meeting_password character varying,
  virtual_platform character varying CHECK (virtual_platform::text = ANY (ARRAY['zoom'::character varying, 'google_meet'::character varying, 'teams'::character varying, 'custom'::character varying, 'other'::character varying]::text[])),
  reminder_sent boolean DEFAULT false,
  reminder_sent_at timestamp with time zone,
  booking_notes text,
  special_requests text,
  metadata jsonb,
  booked_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (booking_id),
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.check_ins (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  membership_id uuid,
  check_in_time timestamp with time zone NOT NULL DEFAULT now(),
  check_out_time timestamp with time zone,
  duration_minutes integer,
  verification_method character varying,
  qr_code_data text,
  check_in_latitude numeric,
  check_in_longitude numeric,
  status character varying DEFAULT 'checked_in'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT check_ins_pkey PRIMARY KEY (id),
  CONSTRAINT check_ins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT check_ins_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT check_ins_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES public.gym_memberships(id)
);
CREATE TABLE public.class_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_id uuid NOT NULL,
  user_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  booking_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  status character varying DEFAULT 'booked'::character varying,
  price numeric,
  payment_status character varying DEFAULT 'pending'::character varying,
  checked_in_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cancelled_at timestamp with time zone,
  CONSTRAINT class_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT class_bookings_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT class_bookings_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  trainer_id uuid,
  name character varying NOT NULL,
  class_type character varying NOT NULL,
  description text,
  difficulty_level character varying,
  image_url text,
  max_capacity integer NOT NULL,
  min_capacity integer DEFAULT 1,
  duration_minutes integer NOT NULL,
  day_of_week character varying,
  start_time time without time zone,
  end_time time without time zone,
  is_active boolean DEFAULT true,
  requires_booking boolean DEFAULT true,
  price_per_class numeric,
  is_included_in_membership boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT classes_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.trainers(id)
);
CREATE TABLE public.daily_nutrition_summary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  total_calories_consumed numeric NOT NULL DEFAULT 0,
  calories_target numeric NOT NULL,
  calories_burned numeric DEFAULT 0,
  calories_net numeric DEFAULT (total_calories_consumed - calories_burned),
  total_protein_grams numeric NOT NULL DEFAULT 0,
  total_carbs_grams numeric NOT NULL DEFAULT 0,
  total_fats_grams numeric NOT NULL DEFAULT 0,
  total_fiber_grams numeric DEFAULT 0,
  total_sugar_grams numeric DEFAULT 0,
  total_sodium_mg numeric DEFAULT 0,
  protein_target_grams numeric,
  carbs_target_grams numeric,
  fats_target_grams numeric,
  total_water_ml integer DEFAULT 0,
  water_goal_ml integer DEFAULT 2000,
  meals_logged integer DEFAULT 0,
  breakfast_logged boolean DEFAULT false,
  lunch_logged boolean DEFAULT false,
  dinner_logged boolean DEFAULT false,
  snacks_count integer DEFAULT 0,
  workout_duration_minutes integer DEFAULT 0,
  workout_calories_burned numeric DEFAULT 0,
  goal_met boolean DEFAULT false,
  protein_goal_met boolean DEFAULT false,
  water_goal_met boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_nutrition_summary_pkey PRIMARY KEY (id),
  CONSTRAINT daily_nutrition_summary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.equipment (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  name character varying NOT NULL,
  category character varying NOT NULL,
  brand character varying,
  model character varying,
  description text,
  specifications text,
  usage_instructions text,
  images ARRAY DEFAULT '{}'::text[],
  video_url text,
  total_count integer NOT NULL DEFAULT 1,
  available_count integer NOT NULL DEFAULT 1,
  is_active boolean DEFAULT true,
  requires_booking boolean DEFAULT false,
  last_maintenance_date date,
  next_maintenance_date date,
  condition character varying DEFAULT 'good'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT equipment_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.equipment_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  equipment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  queue_position integer NOT NULL,
  estimated_wait_minutes integer,
  status character varying DEFAULT 'waiting'::character varying,
  notified_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT equipment_queue_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_queue_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id),
  CONSTRAINT equipment_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT equipment_queue_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.equipment_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  equipment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  start_time timestamp with time zone NOT NULL DEFAULT now(),
  end_time timestamp with time zone,
  planned_duration_minutes integer,
  actual_duration_minutes integer,
  status character varying DEFAULT 'in_use'::character varying,
  reported_issue text,
  issue_severity character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT equipment_usage_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_usage_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id),
  CONSTRAINT equipment_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT equipment_usage_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['chest'::text, 'back'::text, 'shoulders'::text, 'arms'::text, 'legs'::text, 'core'::text, 'cardio'::text, 'fullbody'::text])),
  equipment ARRAY DEFAULT '{}'::text[],
  difficulty text CHECK (difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  instructions ARRAY,
  video_url text,
  image_url text,
  muscle_groups ARRAY,
  is_custom boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercises_pkey PRIMARY KEY (id),
  CONSTRAINT exercises_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.faq (
  faq_id uuid NOT NULL DEFAULT gen_random_uuid(),
  question text NOT NULL,
  answer text NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['payments'::character varying, 'bookings'::character varying, 'trainers'::character varying, 'app_usage'::character varying, 'technical_issues'::character varying, 'account'::character varying, 'subscription'::character varying, 'refunds'::character varying, 'general'::character varying, 'other'::character varying]::text[])),
  keywords ARRAY,
  tags ARRAY,
  is_active boolean DEFAULT true,
  is_popular boolean DEFAULT false,
  display_order integer DEFAULT 0,
  priority integer DEFAULT 0,
  view_count integer DEFAULT 0,
  helpful_count integer DEFAULT 0,
  not_helpful_count integer DEFAULT 0,
  has_video boolean DEFAULT false,
  video_url text,
  has_image boolean DEFAULT false,
  image_url text,
  related_faq_ids ARRAY,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone,
  CONSTRAINT faq_pkey PRIMARY KEY (faq_id)
);
CREATE TABLE public.fitness_goals (
  goal_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  goal_type character varying NOT NULL CHECK (goal_type::text = ANY (ARRAY['weight_loss'::character varying, 'muscle_gain'::character varying, 'endurance'::character varying, 'strength'::character varying, 'flexibility'::character varying, 'general_fitness'::character varying, 'custom'::character varying]::text[])),
  goal_value numeric,
  goal_unit character varying,
  goal_description text,
  target_date date,
  start_value numeric,
  current_value numeric,
  progress_percentage numeric DEFAULT 0 CHECK (progress_percentage >= 0::numeric AND progress_percentage <= 100::numeric),
  is_active boolean DEFAULT true,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fitness_goals_pkey PRIMARY KEY (goal_id),
  CONSTRAINT fitness_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.food_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  brand text,
  serving_size text NOT NULL,
  serving_size_g numeric,
  calories integer NOT NULL,
  protein_g numeric,
  carbs_g numeric,
  fat_g numeric,
  fiber_g numeric,
  sugar_g numeric,
  sodium_mg numeric,
  barcode text,
  is_custom boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT food_items_pkey PRIMARY KEY (id),
  CONSTRAINT food_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.gym_memberships (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  membership_type character varying,
  status character varying DEFAULT 'active'::character varying,
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  end_date date,
  last_visited timestamp with time zone,
  total_visits integer DEFAULT 0,
  payment_status character varying DEFAULT 'pending'::character varying,
  is_favorite boolean DEFAULT false,
  notifications_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gym_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT gym_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT gym_memberships_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.gym_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  comment text NOT NULL,
  photos ARRAY DEFAULT '{}'::text[],
  helpful_count integer DEFAULT 0,
  report_count integer DEFAULT 0,
  is_verified_visit boolean DEFAULT false,
  is_approved boolean DEFAULT true,
  is_hidden boolean DEFAULT false,
  gym_response text,
  gym_response_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gym_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT gym_reviews_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT gym_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.gyms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  address character varying NOT NULL,
  city character varying NOT NULL,
  country character varying NOT NULL,
  postal_code character varying,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  location USER-DEFINED,
  phone_number character varying,
  email character varying,
  website character varying,
  images ARRAY DEFAULT '{}'::text[],
  cover_image text,
  facilities jsonb DEFAULT '[]'::jsonb,
  membership_fee numeric,
  price_range character varying,
  opening_hours jsonb,
  is_24_hours boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  rating numeric DEFAULT 0.0 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  review_count integer DEFAULT 0,
  member_count integer DEFAULT 0,
  current_occupancy integer DEFAULT 0 CHECK (current_occupancy >= 0),
  max_capacity integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gyms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.health_risk (
  risk_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  risk_type character varying NOT NULL CHECK (risk_type::text = ANY (ARRAY['cardiovascular'::character varying, 'diabetes'::character varying, 'obesity'::character varying, 'hypertension'::character varying, 'injury'::character varying, 'overtraining'::character varying, 'general'::character varying]::text[])),
  risk_score integer CHECK (risk_score >= 0 AND risk_score <= 100),
  risk_level character varying CHECK (risk_level::text = ANY (ARRAY['low'::character varying, 'moderate'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  ai_recommendation text,
  contributing_factors jsonb,
  recommended_actions jsonb,
  assessed_at timestamp with time zone DEFAULT now(),
  assessment_method character varying CHECK (assessment_method::text = ANY (ARRAY['ai_analysis'::character varying, 'manual_input'::character varying, 'doctor_consultation'::character varying]::text[])),
  is_current boolean DEFAULT true,
  next_assessment_date date,
  reviewed_by_professional boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT health_risk_pkey PRIMARY KEY (risk_id),
  CONSTRAINT health_risk_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.invoices (
  invoice_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  invoice_no character varying NOT NULL UNIQUE,
  invoice_type character varying CHECK (invoice_type::text = ANY (ARRAY['payment'::character varying, 'refund'::character varying, 'subscription'::character varying, 'topup'::character varying]::text[])),
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  total_amount numeric NOT NULL,
  currency character varying NOT NULL,
  split_details jsonb,
  tax_details jsonb,
  tax_rate numeric,
  tax_id character varying,
  line_items jsonb,
  pdf_url text,
  pdf_generated boolean DEFAULT false,
  pdf_generated_at timestamp with time zone,
  qr_code_data text,
  qr_code_url text,
  gym_id uuid,
  trainer_id uuid,
  booking_id uuid,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'issued'::character varying, 'paid'::character varying, 'partially_paid'::character varying, 'refunded'::character varying, 'canceled'::character varying, 'overdue'::character varying]::text[])),
  payment_method character varying,
  payment_gateway character varying,
  paid_at timestamp with time zone,
  due_date date,
  notes text,
  terms_conditions text,
  invoice_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (invoice_id),
  CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.issue_reports (
  issue_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['bug_report'::character varying, 'payment_issue'::character varying, 'booking_error'::character varying, 'feature_request'::character varying, 'other'::character varying]::text[])),
  title character varying NOT NULL,
  description text NOT NULL,
  device_info jsonb,
  app_version character varying,
  os_version character varying,
  screen_name character varying,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  user_set_priority character varying,
  screenshots jsonb,
  logs_url text,
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'investigating'::character varying, 'in_progress'::character varying, 'fixed'::character varying, 'closed'::character varying, 'wont_fix'::character varying, 'duplicate'::character varying]::text[])),
  resolution_notes text,
  fixed_in_version character varying,
  resolved_at timestamp with time zone,
  is_duplicate boolean DEFAULT false,
  duplicate_of_issue_id uuid,
  assigned_to uuid,
  internal_priority integer,
  estimated_fix_date date,
  actual_fix_date date,
  metadata jsonb,
  tags ARRAY,
  reported_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT issue_reports_pkey PRIMARY KEY (issue_id),
  CONSTRAINT issue_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT issue_reports_duplicate_of_issue_id_fkey FOREIGN KEY (duplicate_of_issue_id) REFERENCES public.issue_reports(issue_id)
);
CREATE TABLE public.meal_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meal_id uuid NOT NULL,
  food_name character varying NOT NULL,
  food_brand character varying,
  serving_size numeric NOT NULL,
  serving_unit character varying NOT NULL,
  calories numeric NOT NULL,
  protein_grams numeric NOT NULL DEFAULT 0,
  carbs_grams numeric NOT NULL DEFAULT 0,
  fats_grams numeric NOT NULL DEFAULT 0,
  fiber_grams numeric DEFAULT 0,
  sugar_grams numeric DEFAULT 0,
  sodium_mg numeric DEFAULT 0,
  external_food_id character varying,
  external_source character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_items_pkey PRIMARY KEY (id),
  CONSTRAINT meal_items_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id)
);
CREATE TABLE public.meals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  meal_type character varying NOT NULL CHECK (meal_type::text = ANY (ARRAY['breakfast'::character varying, 'lunch'::character varying, 'dinner'::character varying, 'snack'::character varying]::text[])),
  meal_name character varying,
  meal_date date NOT NULL DEFAULT CURRENT_DATE,
  meal_time time without time zone NOT NULL DEFAULT CURRENT_TIME,
  total_calories numeric NOT NULL DEFAULT 0,
  protein_grams numeric NOT NULL DEFAULT 0,
  carbs_grams numeric NOT NULL DEFAULT 0,
  fats_grams numeric NOT NULL DEFAULT 0,
  fiber_grams numeric DEFAULT 0,
  sugar_grams numeric DEFAULT 0,
  sodium_mg numeric DEFAULT 0,
  meal_category character varying CHECK (meal_category::text = ANY (ARRAY['vegetarian'::character varying, 'vegan'::character varying, 'high-protein'::character varying, 'high-carb'::character varying, 'low-carb'::character varying, 'keto'::character varying, 'balanced'::character varying, 'other'::character varying]::text[])),
  entry_method character varying NOT NULL CHECK (entry_method::text = ANY (ARRAY['manual'::character varying, 'photo'::character varying, 'barcode'::character varying, 'ai-suggestion'::character varying]::text[])),
  photo_url text,
  barcode_value character varying,
  ai_detected_foods jsonb,
  ai_confidence_score numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meals_pkey PRIMARY KEY (id),
  CONSTRAINT meals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notification_preferences (
  preference_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  notifications_enabled boolean DEFAULT true,
  allow_push boolean DEFAULT true,
  allow_email boolean DEFAULT true,
  allow_sms boolean DEFAULT false,
  payment_push boolean DEFAULT true,
  payment_email boolean DEFAULT true,
  payment_sms boolean DEFAULT false,
  booking_push boolean DEFAULT true,
  booking_email boolean DEFAULT true,
  booking_sms boolean DEFAULT false,
  reward_push boolean DEFAULT true,
  reward_email boolean DEFAULT true,
  reward_sms boolean DEFAULT false,
  offer_push boolean DEFAULT true,
  offer_email boolean DEFAULT true,
  offer_sms boolean DEFAULT false,
  system_push boolean DEFAULT true,
  system_email boolean DEFAULT false,
  system_sms boolean DEFAULT false,
  ai_tips_push boolean DEFAULT true,
  ai_tips_email boolean DEFAULT false,
  ai_tips_sms boolean DEFAULT false,
  workout_push boolean DEFAULT true,
  workout_email boolean DEFAULT false,
  workout_sms boolean DEFAULT false,
  meal_push boolean DEFAULT true,
  meal_email boolean DEFAULT false,
  meal_sms boolean DEFAULT false,
  social_push boolean DEFAULT true,
  social_email boolean DEFAULT false,
  social_sms boolean DEFAULT false,
  sound_enabled boolean DEFAULT true,
  vibration_enabled boolean DEFAULT true,
  quiet_hours_enabled boolean DEFAULT false,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  dnd_enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (preference_id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  notification_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['payment'::character varying, 'booking'::character varying, 'reward'::character varying, 'system'::character varying, 'offer'::character varying, 'achievement'::character varying, 'workout'::character varying, 'meal'::character varying, 'gym'::character varying, 'trainer'::character varying, 'social'::character varying]::text[])),
  linked_screen character varying,
  related_entity_id uuid,
  related_entity_type character varying,
  status character varying DEFAULT 'unread'::character varying CHECK (status::text = ANY (ARRAY['unread'::character varying, 'read'::character varying, 'archived'::character varying, 'deleted'::character varying]::text[])),
  read_at timestamp with time zone,
  is_important boolean DEFAULT false,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  sent_via_push boolean DEFAULT false,
  push_sent_at timestamp with time zone,
  push_status character varying CHECK (push_status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'clicked'::character varying]::text[])),
  sent_via_email boolean DEFAULT false,
  email_sent_at timestamp with time zone,
  email_status character varying CHECK (email_status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'opened'::character varying, 'clicked'::character varying]::text[])),
  sent_via_sms boolean DEFAULT false,
  sms_sent_at timestamp with time zone,
  sms_status character varying CHECK (sms_status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'delivered'::character varying]::text[])),
  action_button_text character varying,
  action_url text,
  action_type character varying,
  expires_at timestamp with time zone,
  is_expired boolean DEFAULT false,
  metadata jsonb,
  icon_name character varying,
  image_url text,
  scheduled_for timestamp with time zone,
  sent_at timestamp with time zone,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (notification_id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_methods (
  payment_method_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  method_type character varying NOT NULL CHECK (method_type::text = ANY (ARRAY['credit_card'::character varying, 'debit_card'::character varying, 'paypal'::character varying, 'apple_pay'::character varying, 'google_pay'::character varying, 'upi'::character varying, 'bank_account'::character varying, 'wallet'::character varying, 'other'::character varying]::text[])),
  gateway_id character varying CHECK (gateway_id::text = ANY (ARRAY['razorpay'::character varying, 'stripe'::character varying, 'paypal'::character varying, 'square'::character varying, 'other'::character varying]::text[])),
  gateway_customer_id character varying,
  gateway_payment_method_id character varying,
  card_last_four character varying,
  card_brand character varying,
  card_expiry_month integer CHECK (card_expiry_month >= 1 AND card_expiry_month <= 12),
  card_expiry_year integer,
  card_holder_name character varying,
  bank_name character varying,
  account_last_four character varying,
  upi_id character varying,
  paypal_email character varying,
  is_default boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  nickname character varying,
  billing_address jsonb,
  verified_at timestamp with time zone,
  added_on timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  expires_at date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (payment_method_id),
  CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  date_of_birth date,
  gender text,
  height_cm numeric,
  current_weight_kg numeric,
  target_weight_kg numeric,
  primary_goal text,
  activity_level text,
  daily_calorie_goal integer,
  daily_protein_goal_g numeric,
  daily_carbs_goal_g numeric,
  daily_fat_goal_g numeric,
  units_system text DEFAULT 'metric'::text,
  onboarding_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  height_unit text DEFAULT 'cm'::text,
  weight_unit text DEFAULT 'kg'::text,
  goal_weight_kg numeric,
  body_type text,
  occupation text,
  occupation_custom text,
  job_activity_level text,
  goal_timeline text,
  workout_environment text,
  workout_types ARRAY,
  equipment_access text,
  session_duration text,
  weekly_workout_days text,
  medical_conditions ARRAY,
  medical_conditions_other text,
  current_symptoms ARRAY,
  past_injuries boolean DEFAULT false,
  injury_details text,
  dietary_restrictions ARRAY,
  dietary_restrictions_other text,
  food_allergies boolean DEFAULT false,
  food_allergy_list text,
  meals_per_day text,
  meal_budget text,
  cuisine_preference text,
  body_photo_url text,
  body_photo_ml_type text,
  body_measurements jsonb,
  track_measurements boolean DEFAULT true,
  wearable_connected boolean DEFAULT false,
  wearable_platform text,
  sleep_hours text,
  stress_level text,
  smokes_or_drinks boolean DEFAULT false,
  age integer,
  weight_kg numeric,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.progress_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  weight_kg numeric,
  body_fat_percentage numeric,
  chest_cm numeric,
  waist_cm numeric,
  hips_cm numeric,
  bicep_left_cm numeric,
  bicep_right_cm numeric,
  thigh_left_cm numeric,
  thigh_right_cm numeric,
  photo_front_url text,
  photo_side_url text,
  photo_back_url text,
  notes text,
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT progress_entries_pkey PRIMARY KEY (id),
  CONSTRAINT progress_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.referral_rewards (
  reward_id uuid NOT NULL DEFAULT gen_random_uuid(),
  reward_stage character varying NOT NULL UNIQUE CHECK (reward_stage::text = ANY (ARRAY['signup'::character varying, 'verification'::character varying, 'subscription'::character varying, 'first_workout'::character varying, 'retention_30days'::character varying, 'retention_60days'::character varying, 'retention_90days'::character varying]::text[])),
  referrer_points integer DEFAULT 0 CHECK (referrer_points >= 0),
  referee_points integer DEFAULT 0 CHECK (referee_points >= 0),
  referrer_cash_amount numeric DEFAULT 0.00 CHECK (referrer_cash_amount >= 0::numeric),
  referee_cash_amount numeric DEFAULT 0.00 CHECK (referee_cash_amount >= 0::numeric),
  referrer_discount_percentage numeric DEFAULT 0.00 CHECK (referrer_discount_percentage >= 0::numeric AND referrer_discount_percentage <= 100::numeric),
  referee_discount_percentage numeric DEFAULT 0.00 CHECK (referee_discount_percentage >= 0::numeric AND referee_discount_percentage <= 100::numeric),
  reward_type character varying CHECK (reward_type::text = ANY (ARRAY['points'::character varying, 'cash'::character varying, 'discount'::character varying, 'combo'::character varying]::text[])),
  reward_currency character varying DEFAULT 'USD'::character varying,
  minimum_purchase_required numeric DEFAULT 0.00,
  requires_previous_stage boolean DEFAULT true,
  is_active boolean DEFAULT true,
  title character varying,
  description text,
  terms_conditions text,
  display_order integer DEFAULT 0,
  reward_expiry_days integer DEFAULT 180,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_rewards_pkey PRIMARY KEY (reward_id)
);
CREATE TABLE public.referrals (
  referral_id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referrer_code character varying NOT NULL,
  referee_id uuid,
  referee_email character varying,
  referee_name character varying,
  referral_code_used character varying NOT NULL,
  referral_status character varying DEFAULT 'pending'::character varying CHECK (referral_status::text = ANY (ARRAY['pending'::character varying, 'signup_completed'::character varying, 'verified'::character varying, 'subscribed'::character varying, 'completed'::character varying, 'expired'::character varying, 'fraud_flagged'::character varying, 'rejected'::character varying]::text[])),
  reward_trigger_stage character varying CHECK (reward_trigger_stage::text = ANY (ARRAY['signup'::character varying, 'verification'::character varying, 'subscription'::character varying, 'first_workout'::character varying, 'retention_30days'::character varying, 'retention_60days'::character varying, 'retention_90days'::character varying]::text[])),
  current_stage character varying DEFAULT 'signup'::character varying,
  referrer_reward_status character varying DEFAULT 'pending'::character varying CHECK (referrer_reward_status::text = ANY (ARRAY['pending'::character varying, 'eligible'::character varying, 'credited'::character varying, 'expired'::character varying, 'canceled'::character varying]::text[])),
  referee_reward_status character varying DEFAULT 'pending'::character varying CHECK (referee_reward_status::text = ANY (ARRAY['pending'::character varying, 'eligible'::character varying, 'credited'::character varying, 'expired'::character varying, 'canceled'::character varying]::text[])),
  referrer_reward_amount numeric DEFAULT 0.00,
  referee_reward_amount numeric DEFAULT 0.00,
  referrer_reward_credited_at timestamp with time zone,
  referee_reward_credited_at timestamp with time zone,
  signup_completed_at timestamp with time zone,
  verification_completed_at timestamp with time zone,
  subscription_started_at timestamp with time zone,
  first_workout_completed_at timestamp with time zone,
  retention_milestone_reached_at timestamp with time zone,
  is_fraud_suspected boolean DEFAULT false,
  fraud_reason text,
  fraud_flagged_at timestamp with time zone,
  referral_source character varying CHECK (referral_source::text = ANY (ARRAY['whatsapp'::character varying, 'instagram'::character varying, 'facebook'::character varying, 'email'::character varying, 'sms'::character varying, 'twitter'::character varying, 'linkedin'::character varying, 'direct_link'::character varying, 'other'::character varying]::text[])),
  utm_source character varying,
  utm_medium character varying,
  utm_campaign character varying,
  referee_ip_address inet,
  referee_device_info jsonb,
  metadata jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT referrals_pkey PRIMARY KEY (referral_id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES auth.users(id),
  CONSTRAINT referrals_referee_id_fkey FOREIGN KEY (referee_id) REFERENCES auth.users(id)
);
CREATE TABLE public.review_helpful_votes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  review_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT review_helpful_votes_pkey PRIMARY KEY (id),
  CONSTRAINT review_helpful_votes_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.gym_reviews(id),
  CONSTRAINT review_helpful_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reward_points_wallet (
  wallet_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  total_points integer DEFAULT 0 CHECK (total_points >= 0),
  available_points integer DEFAULT 0 CHECK (available_points >= 0),
  pending_points integer DEFAULT 0 CHECK (pending_points >= 0),
  expired_points integer DEFAULT 0,
  cash_value numeric DEFAULT 0.00,
  conversion_rate numeric DEFAULT 0.01,
  lifetime_points_earned integer DEFAULT 0,
  lifetime_points_redeemed integer DEFAULT 0,
  lifetime_cash_equivalent numeric DEFAULT 0.00,
  tier_level character varying DEFAULT 'bronze'::character varying CHECK (tier_level::text = ANY (ARRAY['bronze'::character varying, 'silver'::character varying, 'gold'::character varying, 'platinum'::character varying, 'diamond'::character varying]::text[])),
  tier_benefits jsonb,
  last_earned_at timestamp with time zone,
  last_redeemed_at timestamp with time zone,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_points_wallet_pkey PRIMARY KEY (wallet_id),
  CONSTRAINT reward_points_wallet_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reward_transactions (
  transaction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  wallet_id uuid NOT NULL,
  transaction_type character varying NOT NULL CHECK (transaction_type::text = ANY (ARRAY['earned'::character varying, 'redeemed'::character varying, 'expired'::character varying, 'adjusted'::character varying, 'refunded'::character varying, 'bonus'::character varying]::text[])),
  points_amount integer NOT NULL,
  cash_equivalent numeric,
  source character varying CHECK (source::text = ANY (ARRAY['referral_signup'::character varying, 'referral_subscription'::character varying, 'referral_retention'::character varying, 'workout_completion'::character varying, 'achievement'::character varying, 'promotion'::character varying, 'admin_adjustment'::character varying, 'redemption'::character varying, 'expiry'::character varying, 'other'::character varying]::text[])),
  source_id uuid,
  related_referral_id uuid,
  referral_stage character varying,
  redeemed_for character varying CHECK (redeemed_for::text = ANY (ARRAY['wallet_credit'::character varying, 'discount'::character varying, 'membership'::character varying, 'trainer_session'::character varying, 'merchandise'::character varying, 'other'::character varying]::text[])),
  redemption_value numeric,
  applied_to_transaction_id uuid,
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'reversed'::character varying, 'failed'::character varying]::text[])),
  balance_after integer,
  expires_at timestamp with time zone,
  expired boolean DEFAULT false,
  description text,
  notes text,
  metadata jsonb,
  transaction_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_transactions_pkey PRIMARY KEY (transaction_id),
  CONSTRAINT reward_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT reward_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.reward_points_wallet(wallet_id),
  CONSTRAINT reward_transactions_related_referral_id_fkey FOREIGN KEY (related_referral_id) REFERENCES public.referrals(referral_id)
);
CREATE TABLE public.sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_exercise_id uuid NOT NULL,
  set_number integer NOT NULL,
  reps integer,
  weight_kg numeric,
  duration_seconds integer,
  distance_meters numeric,
  rpe integer CHECK (rpe >= 1 AND rpe <= 10),
  is_warmup boolean DEFAULT false,
  completed boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sets_pkey PRIMARY KEY (id),
  CONSTRAINT sets_workout_exercise_id_fkey FOREIGN KEY (workout_exercise_id) REFERENCES public.workout_exercises(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.support_chat (
  chat_id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  sender_type character varying NOT NULL CHECK (sender_type::text = ANY (ARRAY['user'::character varying, 'admin'::character varying, 'agent'::character varying, 'bot'::character varying]::text[])),
  sender_id uuid,
  sender_name character varying,
  message_text text NOT NULL,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'image'::character varying, 'file'::character varying, 'link'::character varying, 'system'::character varying]::text[])),
  attachment_url text,
  attachment_filename character varying,
  attachment_type character varying,
  attachment_size_bytes bigint,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  is_delivered boolean DEFAULT false,
  delivered_at timestamp with time zone,
  is_system_message boolean DEFAULT false,
  metadata jsonb,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_chat_pkey PRIMARY KEY (chat_id),
  CONSTRAINT support_chat_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.support_requests(request_id)
);
CREATE TABLE public.support_requests (
  request_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  ticket_number character varying NOT NULL UNIQUE,
  subject text NOT NULL,
  message text NOT NULL,
  category character varying CHECK (category::text = ANY (ARRAY['bug_report'::character varying, 'payment_issue'::character varying, 'booking_error'::character varying, 'feature_request'::character varying, 'account_issue'::character varying, 'technical_support'::character varying, 'feedback'::character varying, 'complaint'::character varying, 'other'::character varying]::text[])),
  channel character varying NOT NULL CHECK (channel::text = ANY (ARRAY['chat'::character varying, 'email'::character varying, 'call'::character varying, 'in_app'::character varying]::text[])),
  preferred_contact_method character varying,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'pending'::character varying, 'in_progress'::character varying, 'waiting_customer'::character varying, 'resolved'::character varying, 'closed'::character varying, 'reopened'::character varying, 'escalated'::character varying]::text[])),
  assigned_to uuid,
  assigned_at timestamp with time zone,
  resolution text,
  resolved_at timestamp with time zone,
  resolution_time_minutes integer,
  satisfaction_rating integer CHECK (satisfaction_rating >= 1 AND satisfaction_rating <= 5),
  satisfaction_feedback text,
  rated_at timestamp with time zone,
  attachments jsonb,
  related_entity_type character varying,
  related_entity_id uuid,
  internal_notes text,
  tags ARRAY,
  follow_up_required boolean DEFAULT false,
  follow_up_date date,
  submitted_at timestamp with time zone DEFAULT now(),
  last_updated_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT support_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.trainer_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trainer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  session_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text NOT NULL,
  professionalism_rating integer CHECK (professionalism_rating IS NULL OR professionalism_rating >= 1 AND professionalism_rating <= 5),
  knowledge_rating integer CHECK (knowledge_rating IS NULL OR knowledge_rating >= 1 AND knowledge_rating <= 5),
  motivation_rating integer CHECK (motivation_rating IS NULL OR motivation_rating >= 1 AND motivation_rating <= 5),
  is_approved boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trainer_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT trainer_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT trainer_reviews_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.training_sessions(id),
  CONSTRAINT trainer_reviews_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.trainers(id)
);
CREATE TABLE public.trainers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  user_id uuid,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying,
  phone_number character varying,
  photo_url text,
  bio text,
  specializations ARRAY DEFAULT '{}'::text[],
  certifications ARRAY DEFAULT '{}'::text[],
  years_of_experience integer,
  languages ARRAY DEFAULT '{}'::text[],
  price_per_session numeric,
  price_per_hour numeric,
  rating numeric DEFAULT 0.0 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  review_count integer DEFAULT 0,
  total_sessions_completed integer DEFAULT 0,
  available_days jsonb,
  is_available boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trainers_pkey PRIMARY KEY (id),
  CONSTRAINT trainers_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT trainers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.training_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trainer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  session_type character varying,
  title character varying,
  description text,
  scheduled_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  duration_minutes integer NOT NULL,
  status character varying DEFAULT 'scheduled'::character varying,
  price numeric,
  payment_status character varying DEFAULT 'pending'::character varying,
  trainer_notes text,
  client_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cancelled_at timestamp with time zone,
  CONSTRAINT training_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT training_sessions_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.trainers(id),
  CONSTRAINT training_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT training_sessions_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.transactions (
  transaction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  wallet_id uuid,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['wallet_topup'::character varying, 'gym_payment'::character varying, 'trainer_payment'::character varying, 'class_payment'::character varying, 'subscription'::character varying, 'refund'::character varying, 'reward_redemption'::character varying, 'other'::character varying]::text[])),
  amount numeric NOT NULL,
  currency character varying NOT NULL,
  payment_method_id uuid,
  payment_method_type character varying,
  gateway_id character varying,
  gateway_transaction_id character varying,
  gateway_response jsonb,
  split_to_gym numeric,
  split_to_it_company numeric,
  split_calculated boolean DEFAULT false,
  gym_id uuid,
  trainer_id uuid,
  booking_id uuid,
  subscription_id uuid,
  invoice_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'success'::character varying, 'failed'::character varying, 'refunded'::character varying, 'partially_refunded'::character varying, 'disputed'::character varying, 'canceled'::character varying]::text[])),
  refund_amount numeric DEFAULT 0.00,
  refund_reason text,
  refunded_at timestamp with time zone,
  description text,
  metadata jsonb,
  ip_address inet,
  user_agent text,
  transaction_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallet(wallet_id),
  CONSTRAINT transactions_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(payment_method_id),
  CONSTRAINT transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(invoice_id)
);
CREATE TABLE public.user_documents (
  document_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['medical_note'::character varying, 'prescription'::character varying, 'lab_report'::character varying, 'insurance'::character varying, 'waiver'::character varying, 'other'::character varying]::text[])),
  document_name character varying NOT NULL,
  document_url text NOT NULL,
  file_size_bytes bigint,
  mime_type character varying,
  issued_by character varying,
  issue_date date,
  expiry_date date,
  notes text,
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  uploaded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_documents_pkey PRIMARY KEY (document_id),
  CONSTRAINT user_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_preferences (
  preference_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  region_code character varying,
  timezone character varying DEFAULT 'UTC'::character varying,
  currency character varying DEFAULT 'USD'::character varying,
  language character varying DEFAULT 'en'::character varying,
  unit_weight character varying DEFAULT 'kg'::character varying CHECK (unit_weight::text = ANY (ARRAY['kg'::character varying, 'lbs'::character varying]::text[])),
  unit_height character varying DEFAULT 'cm'::character varying CHECK (unit_height::text = ANY (ARRAY['cm'::character varying, 'ft_in'::character varying]::text[])),
  unit_distance character varying DEFAULT 'km'::character varying CHECK (unit_distance::text = ANY (ARRAY['km'::character varying, 'miles'::character varying]::text[])),
  unit_calories character varying DEFAULT 'kcal'::character varying CHECK (unit_calories::text = ANY (ARRAY['kcal'::character varying, 'cal'::character varying]::text[])),
  unit_water character varying DEFAULT 'ml'::character varying CHECK (unit_water::text = ANY (ARRAY['ml'::character varying, 'oz'::character varying]::text[])),
  auto_conversion_enabled boolean DEFAULT true,
  theme character varying DEFAULT 'system'::character varying CHECK (theme::text = ANY (ARRAY['light'::character varying, 'dark'::character varying, 'system'::character varying]::text[])),
  auto_sync_enabled boolean DEFAULT true,
  download_quality character varying DEFAULT 'high'::character varying CHECK (download_quality::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])),
  allow_push boolean DEFAULT true,
  allow_email boolean DEFAULT true,
  allow_sms boolean DEFAULT false,
  notifications_preview boolean DEFAULT true,
  share_activity boolean DEFAULT false,
  profile_visibility character varying DEFAULT 'private'::character varying CHECK (profile_visibility::text = ANY (ARRAY['public'::character varying, 'friends'::character varying, 'private'::character varying]::text[])),
  ai_tips_enabled boolean DEFAULT true,
  ai_voice_language character varying DEFAULT 'en'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (preference_id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  user_id uuid NOT NULL,
  full_name character varying,
  avatar_url text,
  gender character varying CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying, 'other'::character varying, 'prefer_not_to_say'::character varying]::text[])),
  date_of_birth date,
  phone character varying,
  height_cm numeric,
  membership_status character varying DEFAULT 'free'::character varying CHECK (membership_status::text = ANY (ARRAY['free'::character varying, 'premium'::character varying, 'pro'::character varying]::text[])),
  profile_completion_percentage integer DEFAULT 0 CHECK (profile_completion_percentage >= 0 AND profile_completion_percentage <= 100),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  referral_code character varying UNIQUE,
  referred_by character varying,
  is_verified boolean DEFAULT false,
  subscription_status character varying DEFAULT 'none'::character varying CHECK (subscription_status::text = ANY (ARRAY['none'::character varying, 'active'::character varying, 'expired'::character varying, 'canceled'::character varying, 'trial'::character varying]::text[])),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_stats (
  user_id uuid NOT NULL,
  current_streak_days integer DEFAULT 0,
  longest_streak_days integer DEFAULT 0,
  total_workouts integer DEFAULT 0,
  total_workout_minutes integer DEFAULT 0,
  last_activity_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_stats_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallet (
  wallet_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance numeric DEFAULT 0.00 CHECK (balance >= 0::numeric),
  reward_points integer DEFAULT 0 CHECK (reward_points >= 0),
  pending_refunds numeric DEFAULT 0.00 CHECK (pending_refunds >= 0::numeric),
  currency character varying DEFAULT 'USD'::character varying,
  total_spent numeric DEFAULT 0.00,
  total_topped_up numeric DEFAULT 0.00,
  total_refunded numeric DEFAULT 0.00,
  total_rewards_redeemed numeric DEFAULT 0.00,
  is_active boolean DEFAULT true,
  is_frozen boolean DEFAULT false,
  freeze_reason text,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wallet_pkey PRIMARY KEY (wallet_id),
  CONSTRAINT wallet_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.wallet_topup (
  topup_id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  user_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency character varying NOT NULL,
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['credit_card'::character varying, 'debit_card'::character varying, 'paypal'::character varying, 'apple_pay'::character varying, 'google_pay'::character varying, 'upi'::character varying, 'bank_transfer'::character varying, 'other'::character varying]::text[])),
  gateway_used character varying CHECK (gateway_used::text = ANY (ARRAY['razorpay'::character varying, 'stripe'::character varying, 'paypal'::character varying, 'square'::character varying, 'other'::character varying]::text[])),
  gateway_transaction_id character varying,
  transaction_status character varying DEFAULT 'pending'::character varying CHECK (transaction_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'success'::character varying, 'failed'::character varying, 'refunded'::character varying, 'canceled'::character varying]::text[])),
  transaction_ref_no character varying UNIQUE,
  payment_details jsonb,
  failure_reason text,
  notes text,
  initiated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wallet_topup_pkey PRIMARY KEY (topup_id),
  CONSTRAINT wallet_topup_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallet(wallet_id),
  CONSTRAINT wallet_topup_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.water_intake (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  amount_ml integer NOT NULL,
  logged_at timestamp with time zone DEFAULT now(),
  daily_goal_ml integer DEFAULT 2000,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT water_intake_pkey PRIMARY KEY (id),
  CONSTRAINT water_intake_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.wearable_devices (
  device_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_name character varying NOT NULL,
  device_type character varying NOT NULL CHECK (device_type::text = ANY (ARRAY['apple_watch'::character varying, 'fitbit'::character varying, 'samsung_gear'::character varying, 'mi_band'::character varying, 'garmin'::character varying, 'other'::character varying]::text[])),
  device_model character varying,
  device_serial_number character varying,
  sync_status character varying DEFAULT 'disconnected'::character varying CHECK (sync_status::text = ANY (ARRAY['connected'::character varying, 'disconnected'::character varying, 'syncing'::character varying, 'error'::character varying]::text[])),
  last_sync_time timestamp with time zone,
  sync_frequency_minutes integer DEFAULT 30,
  heart_rate_enabled boolean DEFAULT true,
  steps_enabled boolean DEFAULT true,
  sleep_enabled boolean DEFAULT true,
  calories_enabled boolean DEFAULT true,
  blood_pressure_enabled boolean DEFAULT false,
  blood_oxygen_enabled boolean DEFAULT false,
  battery_level integer CHECK (battery_level >= 0 AND battery_level <= 100),
  connection_type character varying CHECK (connection_type::text = ANY (ARRAY['bluetooth'::character varying, 'wifi'::character varying, 'cloud'::character varying]::text[])),
  connected_at timestamp with time zone DEFAULT now(),
  disconnected_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wearable_devices_pkey PRIMARY KEY (device_id),
  CONSTRAINT wearable_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.weight_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  weight_kg numeric NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weight_logs_pkey PRIMARY KEY (id),
  CONSTRAINT weight_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.workout_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_session_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  order_index integer NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT workout_exercises_workout_session_id_fkey FOREIGN KEY (workout_session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT workout_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  frequency_per_week integer,
  is_active boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_plans_pkey PRIMARY KEY (id),
  CONSTRAINT workout_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.workout_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  workout_plan_id uuid,
  title text NOT NULL,
  notes text,
  started_at timestamp with time zone NOT NULL,
  completed_at timestamp with time zone,
  duration_minutes integer,
  total_volume_kg numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT workout_sessions_workout_plan_id_fkey FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id)
);